---
- hosts: all

  tasks:
    - name: ensure git is installed
      apt: pkg={{ item }}  state=installed
      sudo: yes
      with_items:
        - git
        - gnutls-bin
        - python-setuptools
      when: ansible_os_family == 'Debian'

    - name: ensure pip is installed
      easy_install: name=pip state=present
      sudo: yes
      when: ansible_os_family == 'Debian'

    - name: ensure virtualenv stuff is installed
      pip: name={{ item }} state=present
      with_items:
        - virtualenv
        - virtualenvwrapper
        - flake8
      sudo: yes
      when: ansible_os_family == 'Debian'

    - name: create checkout directory
      file: dest={{ ansible_user_dir }}/ansible-checkouts owner={{ ansible_user_id }} group={{ ansible_user_gid }} state=directory

    - name: check out dotfiles
      git: repo=https://github.com/sjahl/dotfiles.git dest={{ ansible_user_dir }}/ansible-checkouts/dotfiles version=HEAD

    - name: create symlinks
      file: src={{ ansible_user_dir }}/ansible-checkouts/dotfiles/{{ item.path }} dest={{ ansible_user_dir }}/{{ item.dest }} state=link
      with_items:
        - { path: 'emacs.d', dest: '.emacs.d' }
        - { path: 'screen-tmux/screenrc', dest: '.screenrc' }
        - { path: 'screen-tmux/tmux.conf', dest: '.tmux.conf' }
        - { path: 'vim/vimrc', dest: '.vimrc' }
        - { path: 'bash/bashrc', dest: '.bashrc' }

