---
- hosts: all
  vars:
    local_home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: ensure git is installed
      apt: pkg={{ item }}  state=installed
      sudo: yes
      with_items:
        - git
        - gnutls-bin

    - name: create checkout directory
      file: dest={{ local_home }}/ansible-checkouts owner={{ ansible_user_id }} group={{ ansible_user_gid }} state=directory

    - name: check out dotfiles
      git: repo=https://github.com/sjahl/dotfiles.git dest={{ local_home }}/ansible-checkouts/dotfiles version=HEAD

    - name: create symlinks
      file: src={{ local_home }}/ansible-checkouts/dotfiles/{{ item.path }} dest={{ local_home }}/{{ item.dest }} state=link
      with_items:
        - { path: 'zsh/zshrc', dest: '.zshrc' }
        - { path: 'emacs.d', dest: '.emacs.d' }
        - { path: 'screen-tmux/screenrc', dest: '.screenrc' }
        - { path: 'screen-tmux/tmux.conf', dest: '.tmux.conf' }
        - { path: 'vim/vimrc', dest: '.vimrc' }
        - { path: 'bash/bashrc', dest: '.bashrc' }

